#include "isb/control_center/control_plane.hpp"

#include <sstream>

namespace isb::control_center {
namespace {
std::string escape_json(const std::string& input) { std::string result; for (char c : input) { if (c == '"' || c == '\\') result += '\\'; result += c; } return result; }
}
const char* to_string(OperationState state) noexcept { switch (state) { case OperationState::Success: return "Success"; case OperationState::Failed: return "Failed"; case OperationState::Unsupported: return "Unsupported"; case OperationState::Unknown: return "Unknown"; case OperationState::PermissionDenied: return "Permission denied"; case OperationState::RequiresRestart: return "Requires restart"; case OperationState::RequiresElevation: return "Requires elevated privileges"; case OperationState::PartiallyApplied: return "Partially applied"; } return "Unknown"; }
const char* to_string(Profile profile) noexcept { switch (profile) { case Profile::Balanced: return "Balanced"; case Profile::Gaming: return "Gaming"; case Profile::Compute: return "Compute"; case Profile::AiTensor: return "AI / Tensor"; case Profile::MaximumPerformance: return "Maximum Performance"; case Profile::LowPower: return "Low Power"; case Profile::Custom: return "Custom"; } return "Custom"; }
const char* to_string(GraphicsBackend backend) noexcept { switch (backend) { case GraphicsBackend::Native: return "Native"; case GraphicsBackend::Dlss: return "DLSS"; case GraphicsBackend::Fsr: return "FSR"; case GraphicsBackend::Xess: return "XeSS"; case GraphicsBackend::OptiScaler: return "OptiScaler"; } return "Unknown"; }
std::string display_capability(cal::CapabilityState state) { switch (state) { case cal::CapabilityState::Available: return "Available"; case cal::CapabilityState::Unavailable: return "Unsupported"; case cal::CapabilityState::Unknown: return "Unknown"; } return "Unknown"; }
bool is_editable(const Control& control) noexcept { return control.editable && control.capability == cal::CapabilityState::Available; }
std::vector<GraphicsBackend> graphics_choices(const ApplicationProfile& application) { return application.compatibility == cal::CapabilityState::Available ? application.compatible_backends : std::vector<GraphicsBackend>{}; }
std::string serialize_application_profile(const ApplicationProfile& profile) { std::ostringstream out; out << "{\"api\":\"" << escape_json(profile.api) << "\",\"compatible_backends\":["; for (std::size_t i = 0; i < profile.compatible_backends.size(); ++i) { if (i) out << ','; out << '"' << to_string(profile.compatible_backends[i]) << '"'; } out << "],\"compatibility\":\"" << cal::to_string(profile.compatibility) << "\",\"executable\":\"" << escape_json(profile.executable) << "\",\"name\":\"" << escape_json(profile.name) << "\",\"profile\":\"" << to_string(profile.profile) << "\"}"; return out.str(); }
Snapshot MockControlPlane::inspect() const { Snapshot snapshot; snapshot.mock = true; auto& c = snapshot.capabilities; c.identity = {"NVIDIA", "Volta", cal::ComputeCapability{7, 0}, cal::GpuVariant::V100_SXM2, "Tesla V100 SXM2 16 GB", "Tesla V100"}; c.compute.cuda_state = cal::CapabilityState::Unknown; c.compute.tensor_cores = {cal::CapabilityState::Available, 1}; c.graphics.vulkan_state = cal::CapabilityState::Unknown; c.hardware = {{cal::CapabilityState::Unavailable}, {cal::CapabilityState::Unavailable}, {cal::CapabilityState::Available, 1}, {cal::CapabilityState::Available}, {cal::CapabilityState::Unknown}, {cal::CapabilityState::Unknown}, {cal::CapabilityState::Unavailable}, {cal::CapabilityState::Unavailable}}; snapshot.telemetry = {{"GPU utilization", std::nullopt}, {"Temperature", std::nullopt}, {"Power draw", std::nullopt}, {"SM clock", std::nullopt}, {"Memory clock", std::nullopt}, {"ECC corrected errors", std::nullopt}}; snapshot.controls = {{"power-limit", "Power limit", cal::CapabilityState::Unknown, std::nullopt, std::nullopt, false, "Capability unknown"}, {"application-clocks", "Application clocks", cal::CapabilityState::Unknown, std::nullopt, std::nullopt, false, "Capability unknown"}, {"persistence", "Persistence mode", cal::CapabilityState::Unknown, std::nullopt, std::nullopt, false, "Capability unknown"}}; snapshot.applications = {{"Example application", "/path/to/application", "Unknown", Profile::Balanced, cal::CapabilityState::Unknown, {}}}; return snapshot; }
OperationPlan MockControlPlane::plan_profile(Profile profile) const { return {{"SCAN", "DETECT", "ANALYZE", "PLAN", "USER REVIEW", "APPLY", "VERIFY"}, {}, OperationState::Unknown, std::string("Profile ") + to_string(profile) + " is a policy template; no changes are proposed without provider evidence."}; }
OperationState MockControlPlane::apply(const OperationPlan&) { return OperationState::Unsupported; }
OperationState MockControlPlane::verify(const OperationPlan&) const { return OperationState::Unknown; }
} // namespace isb::control_center
