#include "isb/control_center/control_plane.hpp"

#include <QApplication>
#include <QComboBox>
#include <QFormLayout>
#include <QFrame>
#include <QHBoxLayout>
#include <QLabel>
#include <QListWidget>
#include <QMainWindow>
#include <QMessageBox>
#include <QPushButton>
#include <QStackedWidget>
#include <QTableWidget>
#include <QVBoxLayout>
#include <QWidget>

using namespace isb::control_center;
namespace {
QWidget* panel(const QString& title) { auto* box = new QWidget; auto* layout = new QVBoxLayout(box); layout->setContentsMargins(12, 10, 12, 10); auto* heading = new QLabel(title); heading->setObjectName("heading"); layout->addWidget(heading); return box; }
void add_rows(QVBoxLayout* layout, const std::vector<Metric>& rows) { auto* form = new QFormLayout; form->setLabelAlignment(Qt::AlignLeft); for (const auto& row : rows) form->addRow(QString::fromStdString(row.label), new QLabel(row.value ? QString::fromStdString(*row.value) : "—")); layout->addLayout(form); }
QString feature(isb::cal::CapabilityState state) { return QString::fromStdString(display_capability(state)); }
class Window final : public QMainWindow {
public:
 Window() : plane_(std::make_unique<MockControlPlane>()), snapshot_(plane_->inspect()) { setWindowTitle("ISB V100 Control Center"); resize(1080, 680); build(); }
private:
 std::unique_ptr<ControlPlane> plane_; Snapshot snapshot_; QStackedWidget* pages_ = nullptr;
 void build() { auto* root = new QWidget; auto* body = new QHBoxLayout(root); body->setContentsMargins(0,0,0,0); auto* nav = new QListWidget; nav->setFixedWidth(152); nav->addItems({"GPU", "TUNING", "OPTIMIZATION", "GRAPHICS"}); nav->setCurrentRow(0); pages_ = new QStackedWidget; pages_->addWidget(gpu()); pages_->addWidget(tuning()); pages_->addWidget(optimization()); pages_->addWidget(graphics()); auto* right = new QVBoxLayout; auto* header = new QLabel("MOCK / SIMULATION  |  Tesla V100  |  GPU —  |  —%  |  — W  |  — MHz  |  Driver: Unknown"); header->setObjectName("header"); right->addWidget(header); right->addWidget(pages_); body->addWidget(nav); body->addLayout(right); connect(nav, &QListWidget::currentRowChanged, pages_, &QStackedWidget::setCurrentIndex); setCentralWidget(root); }
 QWidget* gpu() { auto* page = new QWidget; auto* layout = new QHBoxLayout(page); auto* hardware = panel("GPU"); auto* h = qobject_cast<QVBoxLayout*>(hardware->layout()); auto* f = new QFormLayout; const auto& c=snapshot_.capabilities; f->addRow("Model", new QLabel(QString::fromStdString(c.identity.exact_hardware_variant))); f->addRow("Architecture", new QLabel("GV100 / Volta")); f->addRow("Compute capability", new QLabel("7.0 / SM70")); f->addRow("Tensor Cores", new QLabel(feature(c.hardware.tensor_cores.state))); f->addRow("RT Cores", new QLabel(feature(c.hardware.rt_cores.state))); f->addRow("Optical Flow", new QLabel(feature(c.hardware.optical_flow_accelerator.state))); f->addRow("Display outputs", new QLabel(feature(c.hardware.display_outputs.state))); h->addLayout(f); h->addStretch(); auto* current = panel("CURRENT STATE"); add_rows(qobject_cast<QVBoxLayout*>(current->layout()), snapshot_.telemetry); layout->addWidget(hardware); layout->addWidget(current); return page; }
 QWidget* tuning() { auto* page = new QWidget; auto* layout = new QVBoxLayout(page); auto* profile = new QHBoxLayout; auto* selector=new QComboBox; selector->addItems({"Balanced","Gaming","Compute","AI / Tensor","Maximum Performance","Low Power","Custom"}); auto* review=new QPushButton("Review plan"); profile->addWidget(new QLabel("Profile")); profile->addWidget(selector); profile->addWidget(review); profile->addStretch(); layout->addLayout(profile); auto* table=new QTableWidget(static_cast<int>(snapshot_.controls.size()), 4); table->setHorizontalHeaderLabels({"Control","Current","State","Details"}); for(int i=0;i<static_cast<int>(snapshot_.controls.size());++i){const auto& x=snapshot_.controls[i]; table->setItem(i,0,new QTableWidgetItem(QString::fromStdString(x.label))); table->setItem(i,1,new QTableWidgetItem(x.current?QString::fromStdString(*x.current):"—")); table->setItem(i,2,new QTableWidgetItem(feature(x.capability))); table->setItem(i,3,new QTableWidgetItem(QString::fromStdString(x.detail)));} layout->addWidget(table); connect(review,&QPushButton::clicked,this,[this,selector]{ const auto plan=plane_->plan_profile(static_cast<Profile>(selector->currentIndex())); QMessageBox dialog(this); dialog.setWindowTitle("Requested → Planned → Apply → Verify"); dialog.setText("No hardware change has been made."); dialog.setInformativeText(QString::fromStdString(plan.risk)); dialog.setStandardButtons(QMessageBox::Cancel | QMessageBox::Apply); if(dialog.exec()==QMessageBox::Apply) QMessageBox::information(this,"Apply result",QString::fromStdString(to_string(plane_->apply(plan)))+"; verification: "+QString::fromStdString(to_string(plane_->verify(plan)))); }); return page; }
 QWidget* optimization() { auto* page=new QWidget; auto* layout=new QVBoxLayout(page); auto* title=new QLabel("GAMES & APPLICATIONS"); title->setObjectName("heading"); layout->addWidget(title); auto* table=new QTableWidget(static_cast<int>(snapshot_.applications.size()),5); table->setHorizontalHeaderLabels({"Application","Executable","API","Profile","Compatibility"}); for(int i=0;i<static_cast<int>(snapshot_.applications.size());++i){const auto& a=snapshot_.applications[i]; table->setItem(i,0,new QTableWidgetItem(QString::fromStdString(a.name))); table->setItem(i,1,new QTableWidgetItem(QString::fromStdString(a.executable))); table->setItem(i,2,new QTableWidgetItem(QString::fromStdString(a.api))); table->setItem(i,3,new QTableWidgetItem(QString::fromStdString(to_string(a.profile))); table->setItem(i,4,new QTableWidgetItem(feature(a.compatibility)));} layout->addWidget(table); layout->addWidget(new QLabel("Optimize presents SCAN → DETECT → ANALYZE → PLAN → USER REVIEW → APPLY → VERIFY. Unknown compatibility remains non-actionable.")); return page; }
 QWidget* graphics() { auto* page=new QWidget; auto* layout=new QVBoxLayout(page); auto* form=new QFormLayout; form->addRow("Selected application",new QLabel("No compatible application selected")); form->addRow("Upscaling",new QLabel("Unknown — select an application with verified compatibility")); form->addRow("Frame generation",new QLabel("Unknown — native and compatibility-layer features are distinct")); form->addRow("OptiScaler",new QLabel("External component; not installed in mock mode")); layout->addLayout(form); layout->addWidget(new QLabel("Advanced graphics settings are enabled only when the selected application/backend exposes a safe configuration path.")); layout->addStretch(); return page; }
};
}
int main(int argc,char** argv) { QApplication app(argc,argv); app.setStyleSheet("QWidget{background:#202124;color:#e8eaed;font-size:13px} QListWidget{background:#171819;border:0;padding:8px} QListWidget::item{padding:10px 8px} QListWidget::item:selected{background:#34422d;color:#fff} #header{background:#292b2e;padding:9px;color:#c9e7b9} #heading{font-weight:700;color:#b8df9b} QTableWidget{gridline-color:#3a3c3f;border:1px solid #3a3c3f} QPushButton{background:#4d772f;border:0;padding:7px 12px;color:white} QComboBox{padding:5px;background:#303236}"); Window window; window.show(); return app.exec(); }
